return {
    minimal = {
        extension = {
            editor_script = "lua",
            gui_script = "lua",
            render_script = "lua",
            script = "lua",
        },
    },
    full = {
        extension = {
            appmanifest = "yaml",
            atlas = "proto",
            buffer = "json",
            camera = "proto",
            collection = "proto",
            collectionfactory = "proto",
            collectionproxy = "proto",
            collisionobject = "proto",
            editor_script = "lua",
            factory = "proto",
            fp = "glsl",
            gamepads = "proto",
            go = "proto",
            gui = "proto",
            gui_script = "lua",
            input_binding = "proto",
            label = "proto",
            manifest = "proto",
            material = "proto",
            mesh = "proto",
            model = "proto",
            particlefx = "proto",
            project = "dosini",
            render = "proto",
            render_script = "lua",
            script = "lua",
            script_api = "yaml",
            sound = "proto",
            spinemodel = "proto",
            spinescene = "proto",
            sprite = "proto",
            texture_profiles = "proto",
            tilemap = "proto",
            tilesource = "proto",
            vp = "glsl",
        },
        filename = {
            ["ext.manifest"] = "yaml",
        },
    },
}
