on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

name: Update Defold API

jobs:
  update-defold-api:
    name: Update Defold API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: just-sultanov/setup-babashka@v2
        with:
          version: '1.12.206'
      - id: update-api
        run: |
          echo "DEFOLD_API_VERSION=$(bb scripts/update-defold-api.clj)" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Updated Defold API to ${{ steps.update-api.outputs.DEFOLD_API_VERSION }}"
          commit-message: "Updated Defold API ${{ steps.update-api.outputs.DEFOLD_API_VERSION }}"
          branch: "update/defold-api"
          delete-branch: true
          assignees: atomicptr

